src/Ecommerce/EcommerceBundle/Entity/Media.php
<?php

namespace Ecommerce\EcommerceBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Media
 *
 * @ORM\Table(name="media")
 * @ORM\Entity(repositoryClass="Ecommerce\EcommerceBundle\Repository\MediaRepository")
 * @ORM\HasLifeCycleCallbacks
 */
class Media
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Length(min="2")
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255,nullable=true)
     * @Assert\NotBlank()
     * @Assert\Length(min="4")
     */
    private $path;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="updated_at",type="datetime", nullable=true)
     */
    private $updateAt;

    /**
     * @var File
     */
    private $file;


    public function getUploadRootDir()
    {
        return __DIR__.'/../../../../web/uploads';
    }

    public function getAbsolutePath()
    {
        return null === $this->path ? null : $this->getUploadRootDir().'/'.$this->path;
    }


    /**
     * @ORM\PostLoad()
     */
    public function load()
    {
        $this->updateAt = new \DateTime;
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload()
    {
        $this->tempFile = $this->getAbsolutePath();
        $this->oldFile = $this->getPath();
        $this->updateAt = new \DateTime;

        if(null !== $this->file) $this->path = sha1(uniqid(mt_rand(),true)).'.'.$this->file->guessExtension();
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {
        if(null !== $this->file)
        {
            $this->file->move($this->getUploadRootDir(),$this->path);
            unset($this->file);

            if($this->oldFile != null) unlink($this->tempFile);
        }
    }

    /**
     * @ORM\PreRemove()
     */
    public function preRemoveUpload()
    {
        $this->tempFile = $this->getAbsolutePath();
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
        if(file_exists($this->tempFile)) unlink($this->tempFile);
    }

    public function getAssetPath()
    {
        return 'uploads/'.$this->path;
    }


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set path
     *
     * @param string $path
     *
     * @return Media
     */
    public function setPath($path)
    {
        $this->path = $path;

        return $this;
    }

    /**
     * Get path
     *
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }

    /**
     * @return mixed
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * @param mixed $file
     */
    public function setFile($file)
    {
        $this->file = $file;
    }

}

src/Ecommerce/EcommerceBundle/Entity/Produits.php
<?php

namespace Ecommerce\EcommerceBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Produits
 *
 * @ORM\Table(name="produits")
 * @ORM\Entity(repositoryClass="Ecommerce\EcommerceBundle\Repository\ProduitsRepository")
 */
class Produits
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=100, unique=true)
     * @Assert\NotBlank()
     * @Assert\Length(min="2")
     */
    private $nom;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text", nullable=true)
     */
    private $description;

    /**
     * @var float
     *
     * @ORM\Column(name="prixHT", type="float")
     * @Assert\Type(type="float")
     */
    private $prixHT;

    /**
     * @var bool
     *
     * @ORM\Column(name="disponible", type="boolean")
     */
    private $disponible;

    /**
     * @ORM\OneToOne(targetEntity="Ecommerce\EcommerceBundle\Entity\Media",cascade={"persist","remove"})
     * @ORM\JoinColumn(nullable=false)
     * */
    private $media;


    /**
     * @ORM\ManyToOne(targetEntity="Ecommerce\EcommerceBundle\Entity\Tva",cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     * */
    private $tva;

    /**
     * @ORM\ManyToOne(targetEntity="Ecommerce\EcommerceBundle\Entity\Categories",cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     * */
    private $categorie;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set nom
     *
     * @param string $nom
     *
     * @return Produits
     */
    public function setNom($nom)
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * Get nom
     *
     * @return string
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Produits
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set prixHT
     *
     * @param float $prixHT
     *
     * @return Produits
     */
    public function setPrixHT($prixHT)
    {
        $this->prixHT = $prixHT;

        return $this;
    }

    /**
     * Get prixHT
     *
     * @return float
     */
    public function getPrixHT()
    {
        return $this->prixHT;
    }

    /**
     * Set disponible
     *
     * @param boolean $disponible
     *
     * @return Produits
     */
    public function setDisponible($disponible)
    {
        $this->disponible = $disponible;

        return $this;
    }

    /**
     * Get disponible
     *
     * @return bool
     */
    public function getDisponible()
    {
        return $this->disponible;
    }


    /**
     * Set media
     *
     * @param \Ecommerce\EcommerceBundle\Entity\Media $media
     *
     * @return Produits
     */
    public function setMedia(Media $media)
    {
        $this->media = $media;

        return $this;
    }

    /**
     * Get media
     *
     * @return \Ecommerce\EcommerceBundle\Entity\Media
     */
    public function getMedia()
    {
        return $this->media;
    }

    /**
     * Set tva
     *
     * @param \Ecommerce\EcommerceBundle\Entity\Tva $tva
     *
     * @return Produits
     */
    public function setTva(Tva $tva)
    {
        $this->tva = $tva;

        return $this;
    }

    /**
     * Get tva
     *
     * @return \Ecommerce\EcommerceBundle\Entity\Tva
     */
    public function getTva()
    {
        return $this->tva;
    }

    /**
     * Set categorie
     *
     * @param \Ecommerce\EcommerceBundle\Entity\Categories $categorie
     *
     * @return Produits
     */
    public function setCategorie(Categories $categorie)
    {
        $this->categorie = $categorie;

        return $this;
    }

    /**
     * Get categorie
     *
     * @return \Ecommerce\EcommerceBundle\Entity\Categories
     */
    public function getCategorie()
    {
        return $this->categorie;
    }

}

src/Ecommerce/EcommerceBundle/Form/ProduitsType.php
<?php

namespace Ecommerce\EcommerceBundle\Form;

use Ecommerce\EcommerceBundle\Entity\Categories;
use Ecommerce\EcommerceBundle\Entity\Tva;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProduitsType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom',TextType::class,array('attr'=>array('class'=>'form-control')))
            ->add('description',TextareaType::class,array("required"=>false,'attr'=>array('class'=>'form-control')))
            ->add('prixHT',TextType::class,array('label'=>'PrixHT','attr'=>array('class'=>'form-control')))
            ->add('disponible',CheckboxType::class,array("required"=>false))
            ->add('media',MediaType::class)
            ->add('tva')
            ->add('categorie')
        ;
    }
    
    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Ecommerce\EcommerceBundle\Entity\Produits'
        ));
    }
}

src/Ecommerce/EcommerceBundle/Controller/ProduitsController.php
<?php

namespace Ecommerce\EcommerceBundle\Controller;

use Ecommerce\EcommerceBundle\Entity\Categories;
use Ecommerce\EcommerceBundle\Form\searchType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class ProduitsController extends Controller
{

    public function languageAction(Request $request)
    {
        $locale = $request->getLocale();

        $request->getSession()->set('_locale', $locale);

        $referer = $request->headers->get('referer');

        if (empty($referer)) {
            throw $this->createNotFoundException('Referer not found');
        }

        return $this->redirect($referer);
    }

    public function produitsAction(Request $request,Categories $categorie = null)
    {
        $route = $request->attributes->get('_route');
        
        if($categorie != null)
            $findProduits = $this->getDoctrine()->getRepository('EcommerceBundle:Produits')->findByCategorie($categorie);

        else if( $route == 'produitsCategorie' )
        {
            return $this->render('EcommerceBundle:Default:produits/layout/produits.html.twig',
                array('categorieNotFound'=>true,
                    'produits'=>null));
        }
        else
            $findProduits = $this->getDoctrine()->getRepository('EcommerceBundle:Produits')->findBy(array('disponible'=>1));

        $session = $request->getSession();

        if($session->has('panier'))
            $panier = $session->get('panier');
        else
            $panier = false;


        $produits =  $this->get('knp_paginator')->paginate($findProduits, $request->query->get('page', 1)/*page number*/, 6/*limit per page*/);

        if($categorie != null)
            return $this->render('EcommerceBundle:Default:produits/layout/produits.html.twig', array('categorie'=>$categorie,'produits'=>$produits,'panier'=>$panier));

        return $this->render('EcommerceBundle:Default:produits/layout/produits.html.twig', array('produits'=>$produits,'panier'=>$panier));
    }

    public function presentationAction(Request $request,$id)
    {
        $produit = $this->getDoctrine()->getRepository('EcommerceBundle:Produits')->find($id);

        $session = $request->getSession();

        if($produit)
        {
            if($session->has('panier'))
            {
                $panier = $session->get('panier');

                if(array_key_exists($produit->getId(), $panier ))
                {
                    return $this->render('EcommerceBundle:Default:produits/layout/presentation.html.twig',
                        array('produit'=>$produit,'panier'=>true));
                }
            }
        }

        return $this->render('EcommerceBundle:Default:produits/layout/presentation.html.twig',
            array('produit'=>$produit));
    }

    public function renderFormAction()
    {
        $form = $this->createForm(searchType::class);

        return $this->render('EcommerceBundle:Default:recherche/search.html.twig', array('form'=>$form->createView()));
    }

    public function searchAction(Request $request)
    {
        $form = $this->createForm(new searchType());

        $form->handleRequest($request);

        if ($request->getMethod() === 'POST' && $form->isSubmitted() && $form->isValid()) {

            $search = $form['search']->getData();

            $produits = $this->getDoctrine()->getRepository('EcommerceBundle:Produits')->search($search);

            return $this->render('EcommerceBundle:Default:produits/layout/produits.html.twig', array('search'=>true,'produits'=>$produits));
        }
        else
        {
            return $this->redirectToRoute('produits');
        }
    }
}

src/Ecommerce/EcommerceBundle/Resources/views/Default/produits/layout/presentation.html.twig
{% extends '::layout/layout.html.twig' %}

{% block title %} - {{ produit.nom }}{% endblock %}
{% block description %}{{ produit.description }}{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">

            <div class="col-md-3">
                {% include '::modulesUsed/navigation.html.twig' %}
                {{ render(controller('EcommerceBundle:Panier:menu')) }}
            </div>

            <div class="col-md-9">
                {% if not produit %}
                    <div class="alert alert-danger">{{ 'product_doesnt_existence'|trans }}</div>
                {% else %}
                    <div class="row">
                        <div class="col-md-6">
                            <img src="{{ produit.media.assetPath | imagine_filter('produit') }}" alt="{{ produit.media.name }}" style="max-height:100%;max-width: 100%">
                        </div>

                        <div class="col-md-6">
                            <h4><strong>{{ produit.nom }}</strong></h4>
                            <h5>{{ produit.categorie.nom }}</h5>
                            <blockquote>{{ produit.description }}.</blockquote>
                            <h4>{{ produit.prixHT|tva(produit.tva.multiplicate) }} €</h4>

                            {% if panier is defined %}

                                <div class="alert alert-success">
                                   {{ 'already_exist_in_cart'|trans }} <a href="{{ path('panier') }}">{{ 'cart'|trans }}</a> !
                                </div>

                            {% else %}

                            <form action="{{ path('ajouterAuPanier',{ 'id': produit.id }) }}" method="get">

                                <select name="qte" id="qt" class="col-md-2">
                                    <option value="1" selected>1</option>
                                    {% for i in 2..10 %}
                                    <option value="{{ i }}">{{ i }}</option>
                                        {% endfor %}
                                </select>
                                <br><br>
                                <div>
                                    <button type="submit" class="btn btn-success">{{ 'add_to_cart'|trans }}</button>
                                </div>
                            </form>

                            {% endif %}

                        </div>
                    </div>
                {% endif %}

            </div>
        </div>
    </div>
{% endblock %}

src/Ecommerce/EcommerceBundle/Resources/views/Default/produits/layout/produits.html.twig
{% extends '::layout/layout.html.twig' %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-3">

                {% include '::modulesUsed/navigation.html.twig' %}
                {{  render(controller('EcommerceBundle:Panier:menu')) }}
            </div>

            <div class="col-md-9">

                {% for flashMessage in app.session.flashbag.get('success') %}
                    <div class="alert alert-success">
                        {{ flashMessage }}
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    </div>
                {% endfor %}

                {% if categorieNotFound is defined %}
                    <div class="alert alert-danger">{{ 'no_such_category'|trans }}</div>
                {% elseif not produits %}
                    {% if search is defined %}
                        <div class="alert alert-warning">{{ 'no_search_result'|trans }}</div>
                    {% else %}
                        <div class="alert alert-warning">{{ 'no_product_in_stock'|trans }} </div>
                    {%  endif %}
                {% else %}
                    
                    <div class="row">

                    {% for produit in produits %}

                    <div class="col-sm-4">
                        <div class="thumbnail">
                            <div class="caption">
                                <img src="{{ produit.media.assetPath | imagine_filter('produitThumb') }}"
                                     alt="{{ produit.media.name }}" style="max-height:100%;max-width: 100%" height="150" width="300">
                            </div>
                                <div class="caption">
                                <h4><strong>{{ produit.nom }}</strong></h4>
                                <p>{{ produit.prixHT|tva(produit.tva.multiplicate) }} €</p>
                                <a class="btn btn-primary" href="{{ path('presentation',{ 'id': produit.id }) }}">{{ 'more_info'|trans }}</a>
                                {% if panier[produit.id] is not defined %}
                                     <a class="btn btn-s" href="{{ path('ajouterAuPanier',{ 'id': produit.id }) }}">{{ 'add_to_cart'|trans }}</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    </div>
                    <div class="row pull-right">
                        {{ knp_pagination_render(produits) }}
                    </div>
                {% endif %}

            </div>
        </div>
    </div>
{% endblock %}